<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Title>ConfiguredSqlConnection.SqlServer</Title>
	<PackageTags>Database SQL EF SqlServer</PackageTags>
	<Description>SQL Server provider for ConfiguredSqlConnection.Abstractions.</Description>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConfiguredSqlConnection.Abstractions\ConfiguredSqlConnection.Abstractions.csproj" />
  </ItemGroup>

</Project>
