<Project>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsTestProject)' != 'true'">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>2.0.1</Version>
		<PackageReleaseNotes>https://github.com/The-Poolz/ConfiguredSqlConnection/releases/tag/v2.0.1</PackageReleaseNotes>
		<Authors>Senia,ArdenHide,Lomet</Authors>
		<Company>The-Poolz</Company>
		<PackageProjectUrl>https://github.com/The-Poolz/ConfiguredSqlConnection</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/The-Poolz/ConfiguredSqlConnection</RepositoryUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsTestProject)' != 'true'">
		<None Include="$(MSBuildThisFileDirectory)LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="$(MSBuildThisFileDirectory)README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>